[package]
name = "gloomander-save"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.33.0", features = ["full"] }
sqlx = { version = "0.7", features = [ "runtime-tokio", "sqlite" ] }
anyhow = "1.0.75"
futures = "0.3.28"
reqwest = { version = "0.11.22", features = ["json"] }
image = "0.24.7"
